---
- name: Create user
  hosts: all
  become: true

  tasks:
    - name: Create page administrator
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        comment: Page administrator
        group: sudo
        append: true
        create_home: true
    - name: Set new user ssh key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', ssh_key_path) }}"
