---
- name: Disable root access
  hosts: all
  become: true
  tasks:
    - name: Disable root access
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        backup: true
    - name: Disable password access
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication"
        line: "PasswordAuthentication no"
      notify:
        - Restart ssh

  handlers:
    - name: Restart ssh
      ansible.builtin.systemd_service:
        name: sshd
        state: restarted
