---
- name: Install nginx
  hosts: all
  become: true
  tasks:
    - name: Install nginx package
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
    
    - name: Configure nginx conf
      ansible.builtin.copy:
        src: ../configs/nginx.conf
        dest: /etc/nginx/nginx.conf
        force: true

    - name: Delete unnecessary folders
      ansible.builtin.shell:
        chdir: /etc/nginx/
        cmd: rm -rf sites-* && touch removed
        creates: /etc/nginx/removed