---
- name: Configure page config and reload nginx
  hosts: all
  become: true
  tasks:
    - name: Setup nginx page file
      ansible.builtin.copy:
        src: ../configs/page.conf
        dest: /etc/nginx/conf.d
        force: true
        mode: '750'
    - name: Reload nginx process
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
